import {CATS} from "./constants.js";
import {fmtDate} from "./styles.js";

export const SCENARIOS=[
  {id:"within_params",label:"Defectos dentro de parámetros",desc:"Todo está dentro del rango aceptable de Cartama",concept:"not_proceeds",icon:"✓",color:"#2D6A4F"},
  {id:"post_arrival",label:"Atribuible a post-arribo",desc:"Defecto real pero causado por manejo después de la llegada",concept:"not_proceeds",icon:"🚚",color:"#1565C0"},
  {id:"shared",label:"Responsabilidad compartida",desc:"Defecto confirmado, ambas partes tienen responsabilidad",concept:"negotiable",icon:"🤝",color:"#E65100"},
  {id:"origin",label:"Defecto confirmado de origen",desc:"El defecto viene de planta/cosecha, responsabilidad de Cartama",concept:"proceeds",icon:"🌱",color:"#CC0000"},
  {id:"transit",label:"Problema de tránsito/atmósfera",desc:"Temperatura o atmósfera fuera de parámetros durante el transporte",concept:"proceeds",icon:"🌡️",color:"#CC0000"},
  {id:"need_info",label:"Información insuficiente",desc:"No hay datos suficientes para tomar una posición definitiva",concept:null,icon:"📋",color:"#6C757D"},
];

export function buildScenarioResponse(scenarioId,lang,d){
  const g=lang==="en"?`Dear ${d.contact||d.client},`:`Estimado/a ${d.contact||d.client},`;
  const s=lang==="en"?`Best regards,\n[Name]\nQuality Department — Cartama`:`Cordialmente,\n[Nombre]\nDepartamento de Calidad — Cartama`;
  const arrF=fmtDate(d.arrival,lang);
  const defNames=(d.defects||[]).map(x=>lang==="en"?x.name:x.es);
  const defList=defNames.length>0?defNames.join(", "):"the reported issues";
  const defListEs=defNames.length>0?defNames.join(", "):"los hallazgos reportados";

  if(lang==="en"){
    const cr=`container ${d.containers}${arrF?`, which arrived on ${arrF}`:""}`;
    const T={
      "within_params":`${g}\n\nFollowing our thorough review of ${cr}, including the complete traceability analysis, plant counter-samples, and quality records, we would like to share our findings.\n\nIn what concerns ${defList}, all reported findings remain within our acceptable quality parameters as established in our Hass Avocado Grading standards. The fruit was packed and dispatched meeting the required quality criteria, and the defect levels observed do not pose a risk to the commercial viability of the product.\n\n${d.catMismatch?`We would also like to note that this container was dispatched as ${CATS.find(c=>c.id===d.catCartama)?.label||""}, and the quality at dispatch was consistent with this classification.\n\n`:""}Our transit records confirm that temperature and controlled atmosphere parameters were maintained within the established ranges throughout the journey.\n\nBased on the above, the claims are not applicable.\n\nWe remain available for any further discussion and value our continued partnership.\n\n${s}`,

      "post_arrival":`${g}\n\nWe have completed the traceability review for ${cr} and would like to share our assessment.\n\nRegarding ${defList}, our analysis indicates that the quality at the time of dispatch was within acceptable parameters. The plant counter-samples taken during packing did not show the defect levels reported upon arrival.\n\nFurthermore, our transit records confirm that temperature and controlled atmosphere parameters were maintained within the established ranges throughout the journey. There is no record of conditions during transport, storage, or handling at the destination facility that we can verify, and these post-arrival factors can significantly influence fruit quality and shelf life.\n\nBased on our findings, the reported conditions are consistent with post-arrival handling rather than origin or transit factors. Therefore, the claims are not applicable.\n\nWe remain open to discussing this further and sharing additional data if needed.\n\n${s}`,

      "shared":`${g}\n\nWe have completed the traceability analysis for ${cr} and would like to share our findings and proposed resolution.\n\nRegarding ${defList}, our review indicates that while the fruit was dispatched within quality parameters, some of the reported findings may have contributing factors from both origin and post-arrival conditions.\n\nIn the interest of maintaining our strong commercial relationship and reaching a fair outcome for both parties, we propose a collaborative resolution. We are open to discussing a negotiated settlement that reflects the shared nature of these findings.\n\nWe would welcome the opportunity to review this together and reach a mutually agreeable resolution. Please let us know your availability to discuss next steps.\n\n${s}`,

      "origin":`${g}\n\nFollowing the complete traceability analysis for ${cr}, we would like to share our findings.\n\nRegarding ${defList}, our internal review — including plant counter-samples and quality records — confirms that the reported defect levels are consistent with conditions at origin. We acknowledge the quality findings and take full responsibility.\n\nOur Quality team has already initiated corrective actions with the relevant productive units to prevent recurrence in future shipments.\n\nWe will proceed with the claim as reported.\n\nWe value your partnership and are committed to delivering the quality standards you expect.\n\n${s}`,

      "transit":`${g}\n\nWe have completed the traceability review for ${cr}, with particular attention to transit conditions.\n\nOur analysis of the temperature and controlled atmosphere records reveals that parameters were outside the established ranges during transit. This deviation is consistent with the quality findings reported upon arrival regarding ${defList}.\n\nWe acknowledge that the transit conditions likely contributed to the defects observed, and we accept responsibility for this shipment.\n\nWe will proceed with the claim.\n\nCorrective measures have been implemented to prevent similar transit issues going forward.\n\n${s}`,

      "need_info":`${g}\n\nThank you for your communication regarding ${cr}. We have conducted an initial review of the reported findings concerning ${defList}.\n\nIn order to provide you with a definitive assessment, we would need the following additional information:\n\n• [Specify information needed — e.g., temperature records at destination, detailed QC report, photos of specific pallets, storage conditions after arrival]\n\nOnce we receive this, we will be able to complete our analysis and provide you with our final position.\n\nWe appreciate your collaboration and look forward to resolving this together.\n\n${s}`,
    };
    return T[scenarioId]||"";
  }
  else{
    const cr=`contenedor ${d.containers}${arrF?`, el cual llegó el ${arrF}`:""}`;
    const T={
      "within_params":`${g}\n\nTras la revisión exhaustiva del ${cr}, incluyendo el análisis completo de trazabilidad, contramuestras de planta y registros de calidad, nos permitimos compartir nuestros hallazgos.\n\nEn lo que respecta a ${defListEs}, todos los hallazgos reportados se encuentran dentro de nuestros parámetros de calidad aceptables según los estándares de nuestro Hass Avocado Grading. La fruta fue empacada y despachada cumpliendo los criterios de calidad requeridos, y los niveles de defectos observados no representan un riesgo para la viabilidad comercial del producto.\n\n${d.catMismatch?`Cabe señalar que este contenedor fue despachado como ${CATS.find(c=>c.id===d.catCartama)?.label||""}, y la calidad al despacho fue consistente con esta clasificación.\n\n`:""}Nuestros registros de tránsito confirman que los parámetros de temperatura y atmósfera controlada se mantuvieron dentro de los rangos establecidos durante todo el trayecto.\n\nCon base en lo anterior, los reclamos no son aplicables.\n\nQuedamos a su disposición para cualquier consulta adicional y valoramos nuestra relación comercial.\n\n${s}`,

      "post_arrival":`${g}\n\nHemos completado la revisión de trazabilidad del ${cr} y nos permitimos compartir nuestra evaluación.\n\nRespecto a ${defListEs}, nuestro análisis indica que la calidad al momento del despacho se encontraba dentro de los parámetros aceptables. Las contramuestras de planta tomadas durante el empaque no presentaron los niveles de defectos reportados al arribo.\n\nAsimismo, nuestros registros de tránsito confirman que los parámetros de temperatura y atmósfera controlada se mantuvieron dentro de los rangos establecidos durante todo el trayecto. No contamos con registros de las condiciones durante el transporte, almacenamiento o manejo en las instalaciones de destino, factores que pueden influir significativamente en la calidad y vida útil de la fruta.\n\nCon base en nuestros hallazgos, las condiciones reportadas son consistentes con el manejo post-arribo más que con factores de origen o tránsito. Por lo tanto, los reclamos no son aplicables.\n\nEstamos abiertos a discutir esto en mayor detalle y compartir datos adicionales si lo requieren.\n\n${s}`,

      "shared":`${g}\n\nHemos completado el análisis de trazabilidad del ${cr} y nos permitimos compartir nuestros hallazgos y propuesta de resolución.\n\nRespecto a ${defListEs}, nuestra revisión indica que si bien la fruta fue despachada dentro de parámetros de calidad, algunos de los hallazgos reportados pueden tener factores contribuyentes tanto de origen como de condiciones post-arribo.\n\nEn interés de mantener nuestra sólida relación comercial y alcanzar un resultado justo para ambas partes, proponemos una resolución colaborativa. Estamos abiertos a discutir un acuerdo negociado que refleje la naturaleza compartida de estos hallazgos.\n\nNos encantaría la oportunidad de revisar esto juntos y llegar a una resolución mutuamente satisfactoria. Por favor háganos saber su disponibilidad para discutir los siguientes pasos.\n\n${s}`,

      "origin":`${g}\n\nTras el análisis completo de trazabilidad del ${cr}, nos permitimos compartir nuestros hallazgos.\n\nRespecto a ${defListEs}, nuestra revisión interna — incluyendo contramuestras de planta y registros de calidad — confirma que los niveles de defectos reportados son consistentes con condiciones de origen. Reconocemos los hallazgos de calidad y asumimos la responsabilidad.\n\nNuestro equipo de Calidad ya ha iniciado acciones correctivas con las unidades productivas correspondientes para prevenir recurrencia en futuros envíos.\n\nProcederemos con el reclamo según lo reportado.\n\nValoramos su confianza y estamos comprometidos con entregar los estándares de calidad que esperan.\n\n${s}`,

      "transit":`${g}\n\nHemos completado la revisión de trazabilidad del ${cr}, con especial atención a las condiciones de tránsito.\n\nNuestro análisis de los registros de temperatura y atmósfera controlada revela que los parámetros estuvieron fuera de los rangos establecidos durante el tránsito. Esta desviación es consistente con los hallazgos de calidad reportados al arribo respecto a ${defListEs}.\n\nReconocemos que las condiciones de tránsito probablemente contribuyeron a los defectos observados, y aceptamos la responsabilidad por este envío.\n\nProcederemos con el reclamo.\n\nSe han implementado medidas correctivas para prevenir situaciones similares en el futuro.\n\n${s}`,

      "need_info":`${g}\n\nGracias por su comunicación respecto al ${cr}. Hemos realizado una revisión inicial de los hallazgos reportados respecto a ${defListEs}.\n\nPara poder proporcionarle una evaluación definitiva, necesitaríamos la siguiente información adicional:\n\n• [Especificar información necesaria — ej: registros de temperatura en destino, reporte QC detallado, fotos de pallets específicos, condiciones de almacenamiento post-arribo]\n\nUna vez recibida, podremos completar nuestro análisis y proporcionarle nuestra posición final.\n\nAgradecemos su colaboración y esperamos resolver esto de manera conjunta.\n\n${s}`,
    };
    return T[scenarioId]||"";
  }
}
